### ISSUE TITLE
Lua error 

### ISSUE THREAD

**Issue by Aka7tsu4** [mcNuggets1/mg_gun_base#4]
[ERROR] addons/mg_gun_base-master/lua/weapons/mg_gun_base/cl_init.lua:470: attempt to call method 'GetUnpredictedAiming' (a nil value)
  1. func - addons/mg_gun_base-master/lua/weapons/mg_gun_base/cl_init.lua:470
   2. unknown - gamemodes/base/gamemode/cl_init.lua:552

[ERROR] addons/mg_gun_base-master/lua/weapons/mg_nade_base/shared.lua:73: 'end' expected (to close 'function' at line 63) near 'en'
1. unknown - addons/mg_gun_base-master/lua/weapons/mg_nade_base/shared.lua:0

**Comment by mcNuggets1** [comment]
How the heck are you managing to get these errors?

**Comment by Aka7tsu4** [comment]
Just taking a gun in my hands
do you have steam? can give you me ur steam name for better talking?

**Comment by mcNuggets1** [comment]
I can't take a look at your issues, right now.
I got time tomorrow.

**Comment by Aka7tsu4** [comment]
... ehww.

**Comment by mcNuggets1** [comment]
But I can tell you, as far as I looked on your issue, it is likely your issue.
The second error  shouldn't exist in the stable branch.
Line 73 is missing an "end".
But there is an "en". wow.
